#!/bin/bash
#oem view
PARM="-h"
PORT="8443"
ShowOemViewExample()
{
   echo -e "Oem View example:\n\033[31;49;5;1m bash oat_view_oem -h HOSTNAME_OF_OAT-APPRAISER\033[0m"
}

if [ $# -lt 2 ];then
  echo "parm num error!"
  ShowOemViewExample
  exit 0
fi
if [ $1 != $PARM ];then
  echo "parm error!"
  ShowOemViewExample
  exit 0
fi

HOSTNAME="$2"
view_os()
{
     curl --cacert ./certfile.cer -H "Content-Type: application/json" \
     -X GET https://$HOSTNAME:$PORT/WLMService/resources/oem -ssl3
}

view_os
echo -e "\n"
