#!/bin/bash
#create atag script
ADD_PARM="-a"
EDIT_PARM="-e"
DEL_PARM="-d"
HOST_PARM="-h"
FILE_PARM="-f"
HOST_NAME=""
IP_ADDRESS=""
INFO=""
PREFIX="@"
CERTID=""
PORT=8080
ShowExample()
{
  echo -e "Add  asset tag example:\033[31;49;5;1m bash oat_atag -a <HOST_TO_BE_TAGGED_IP_ADDRESS> -h <HOSTNAME_OF_OAT-APPRAISER> -f <TAGS_FILENAME.xml>\033[0m"
  echo -e "Del asset tag example:\033[31;49;5;1m bash oat_atag -d <CERTID_TO_BE_DELETED> -h <HOSTNAME_OF_OAT-APPRAISER>\033[0m"
}

if [ $1 == $ADD_PARM ] &&  [ $# -lt 6 ];then
  echo "add"
  echo "parm num error!"
  ShowExample
  exit 0
fi

if [ $1 == $ADD_PARM ];then
  if [ $3 != $HOST_PARM ];then
    echo "-f parm error! 2"
    ShowExample
    exit 1
  else
    HOST_NAME="$4"
  fi
  if [ $5 != $FILE_PARM ];then
    echo "-f parm error! 3"
    ShowExample
    exit 1
  else
    INFO="$6"
  fi
  IP_ADDRESS="$2"
fi


if [ $1 == $DEL_PARM ] && [ $# -lt 4 ];then
  echo "add"
  echo "parm num error!"
  ShowExample
  exit 0
fi

if [ $1 == $DEL_PARM ];then
  if [ $3 != $HOST_PARM ];then
    echo "-f parm error! 1"
    ShowExample
    exit 1
  else
    HOST_NAME="$4"
  fi
  CERTID="$2"
fi

#if [ $3 != $HOST_PARM ];then
#    echo "-f parm error!"
#    ShowExample
#    exit 1
#  else
#    HOST_NAME="$4"
#  fi


#if [ $5 != $FILE_PARM ];then
#  echo "-f parm error!"
#  ShowExample
#  exit 
#else
#    INFO="$6"
#fi


#if [ $1 != $ADD_PARM ];then
#   echo "-a parm error!"
#   ShowExample
#   exit 1
#else
#   IP_ADDRESS="$2"
# fi

#if [ $1 == $ADD_PARM ];then
#   IP_ADDRESS="$2"
#elif [$1 == $DEL_PARM ];then
#   CERTID="$2"
#else
#   echo "-a parm error!"
#   ShowExample
#   exit 1
#fi


#if [ $1 == $DEL_PARM ];then
#  INFO="`echo "$4" | awk -F{ '{print $2}'| awk -F} '{print $1}'\
#        | sed 's/\"//g' | sed 's/:/=/g' | sed 's/ /%20/g'`"
#else
#  INFO="$4"
#fi

addTAG() 
{
  echo "$PREFIX$INFO"
  curl -H "Accept: application/pkix-cert" -H "Content-Type: application/xml" \
       -X POST -d "$PREFIX$INFO"  "http://$HOST_NAME:$PORT/AttestationService/resources/tag-certificate-requests-rpc/provision?subject=$IP_ADDRESS"
}

editOEM()
{
  curl --cacert certfile.cer -H "Content-Type: application/json" \
        -X PUT -d "$INFO" "https://$HOST_NAME:$PORT/WLMService/resources/oem" 
}

delTAG()
{
  curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "" "http://$HOST_NAME:$PORT/AttestationService/resources/tag-certificate-requests-rpc/revoke-tag-certificate?certId=$CERTID"
}

case $1 in
      $ADD_PARM)
           echo "add TAG:"
           addTAG
      ;;
      $DEL_PARM)
           echo "del TAG:"
           delTAG
      ;;
      *)
      echo "Usage oat_atag {-a|-e|-d}"
      ShowExample
      exit 3
esac
echo -e "\n"
