#!/bin/bash
#create mles script
ADD_PARM="-a"
EDIT_PARM="-e"
DEL_PARM="-d"
HOST_PARM="-h"
HOST_NAME=""
INFO=""
PORT=8443

if [ $# -lt 4 ];then
  echo "parm num error!"
  exit 0
fi

if [ $2 != $HOST_PARM ];then
  echo "-h parm error!"
  exit 1
else
  HOST_NAME="$3"
fi

if [ $1 == $DEL_PARM ];then
  INFO="`echo "$4" | awk -F{ '{print $2}'| awk -F} '{print $1}'\
        | sed 's/\"//g' | sed 's/:/=/g' | sed 's/,/\&/g'| sed 's/ /%20/g'`"
else
  INFO="$4"
fi

addMLE() 
{
  curl --cacert certfile.cer -H "Content-Type: application/json" \
       -X POST -d "$INFO" "https://$HOST_NAME:$PORT/WLMService/resources/mles" -ssl3
}

editMLE()
{
  curl --cacert certfile.cer -H "Content-Type: application/json" \
        -X PUT -d "$INFO" "https://$HOST_NAME:$PORT/WLMService/resources/mles" -ssl3
}

delMLE()
{
  curl --cacert certfile.cer \
        -X DELETE  "https://$HOST_NAME:$PORT/WLMService/resources/mles?$INFO"  -ssl3
}

case $1 in
      $ADD_PARM)
           echo "add MLE:"
           addMLE
      ;;
      $EDIT_PARM)
           echo "edit MLE:"
           editMLE
      ;;
      $DEL_PARM)
           echo "del MLE:"
           delMLE
      ;;
      *)
      echo "Usage oat_mles {-a|-e|-d}"
      exit 3
esac
echo -e "\n"
