#!/bin/bash

config_dir=/etc/intel/cloudsecurity
if [ -d $config_dir ];then
    rm -rf $config_dir
fi
mkdir -p $config_dir
echo -ne "Please enter the Attestation Server's IP[127.0.0.1]: "
read HOST_NAME
if [ "$HOST_NAME" = "" ];then
        HOST_NAME=127.0.0.1
fi


echo "mtwilson.api.baseurl=https://$HOST_NAME:8181
mtwilson.api.ssl.policy=TRUST_FIRST_CERTIFICATE
mtwilson.db.driver=com.mysql.jdbc.Driver
mtwilson.db.url=jdbc:mysql://localhost/mw_as 
mtwilson.db.user=root
mtwilson.db.password=password" > /etc/intel/cloudsecurity/mtwilson.properties

echo "PrivacyCaUrl=https://$HOST_NAME:8181/HisPrivacyCAWebServices2
PrivacyCaSubjectName=HIS_Privacy_CA
PrivacyCaPassword=***replace***
EndorsementCaSubjectName=Endorsement_CA_Rev_1
EndorsementCaPassword=***replace***
CertValidityDays=3652
AikAuth=1111111111111111111111111111111111111111" > /etc/intel/cloudsecurity/privacyca-client.properties

echo "ClientFilesDownloadUsername=admin
ClientFilesDownloadPassword=password" > /etc/intel/cloudsecurity/PrivacyCA.properties

echo "com.intel.mountwilson.as.trustagent.timeout=3
com.intel.mountwilson.as.attestation.hostTimeout=60
com.intel.mountwilson.as.home=/var/opt/intel/aikverifyhome
com.intel.mountwilson.as.openssl.cmd=openssl.sh
saml.key.alias=samlkey1
saml.keystore.file=SAML.jks
saml.keystore.password=changeit
saml.validity.seconds=3600
saml.issuer=https://$HOST_NAME:8181 
saml.key.password=changeit
privacyca.server=$HOST_NAME
com.intel.mtwilson.as.business.trust.sleepTime=1" > /etc/intel/cloudsecurity/attestation-service.properties

echo "mtwilson.tdbp.keystore.dir=/etc/intel/cloudsecurity
mtwilson.tdbp.keystore.password=password
imagesRootPath = images/
trustUnknow = images/Unknown.png
trustTure = images/Trusted.png
trustFalse = images/UnTrusted.png
ubuntu = images/ubuntu.png
vmware = images/vmware.png
suse = images/suse.png
kvm = images/kvm.png
xen = images/xen.png
mtwilson.tdbp.sessionTimeOut = 1800
mtwilson.tdbp.paginationRowCount = 10" > /etc/intel/cloudsecurity/trust-dashboard.properties

echo "mtwilson.wlmp.keystore.dir=/etc/intel/cloudsecurity
mtwilson.wlmp.keystore.password=password
mtwilson.wlmp.openSourceHypervisors=KVM;Xen
mtwilson.wlmp.sessionTimeOut=1800
mtwilson.wlmp.pagingSize=8" > /etc/intel/cloudsecurity/whitelist-portal.properties

