# Important! Ensure that the tabs are maintained.
# Converting tabs to spaces is an error in Makefiles
install:
	mkdir -p /var/opt/intel/aikverifyhome/bin
	mkdir -p /var/opt/intel/aikverifyhome/data
	chmod 755 openssl.sh
	cp openssl.sh /var/opt/intel/aikverifyhome/bin
